[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 2

[[main]]
  identifier = "showcase"
  name = "Projects"
  url = "showcase"
  weight = 6

[[main]]
  identifier = "publication"
  name = "Essay"
  url = "publication"
  weight = 7